language: cpp

matrix:
    include:
        - os: linux
          before_install:
            - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
            - sudo apt-get update
          install:
            - sudo apt-get install qt58base qt58svg qt58charts-no-lgpl qt58xmlpatterns
            - source /opt/qt58/bin/qt58-env.sh
          script:
            - /opt/qt58/bin/qmake PREFIX=/usr
            - make
        - os: windows
          install:
            - set QTDIR=C:\Qt\5.8\mingw53_32
            - choco install -y InnoSetup
            - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
          build_script:
            - qmake
            - mingw32-make
         






