######################################################################
# Automatically generated by qmake (3.1) Tue Oct 23 17:50:22 2018
######################################################################

TEMPLATE = app
TARGET = LixTalk-client
INCLUDEPATH += .
QT += core network gui widgets sql
# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.

DEFINES += QT_DEPRECATED_WARNINGS
CONFIG += c++11
DESTDIR = ./build
OBJECTS_DIR = ./build/obj
UI_DIR = ./build/ui
MOC_DIR = ./build/moc
RCC_DIR = ./build/rcc
# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += LixTalk-client/client.h \
           LixTalk-client/DbConnector.h \
           LixTalk-client/LixTalk.h \
           LixTalk-client/MainWindow.h \
           LixTalk-client/message.h \
           LixTalk-client/rapidjson/allocators.h \
           LixTalk-client/rapidjson/cursorstreamwrapper.h \
           LixTalk-client/rapidjson/document.h \
           LixTalk-client/rapidjson/encodedstream.h \
           LixTalk-client/rapidjson/encodings.h \
           LixTalk-client/rapidjson/filereadstream.h \
           LixTalk-client/rapidjson/filewritestream.h \
           LixTalk-client/rapidjson/fwd.h \
           LixTalk-client/rapidjson/istreamwrapper.h \
           LixTalk-client/rapidjson/memorybuffer.h \
           LixTalk-client/rapidjson/memorystream.h \
           LixTalk-client/rapidjson/ostreamwrapper.h \
           LixTalk-client/rapidjson/pointer.h \
           LixTalk-client/rapidjson/prettywriter.h \
           LixTalk-client/rapidjson/rapidjson.h \
           LixTalk-client/rapidjson/reader.h \
           LixTalk-client/rapidjson/schema.h \
           LixTalk-client/rapidjson/stream.h \
           LixTalk-client/rapidjson/stringbuffer.h \
           LixTalk-client/rapidjson/writer.h \
           LixTalk-client/rapidjson/error/en.h \
           LixTalk-client/rapidjson/error/error.h \
           LixTalk-client/rapidjson/internal/biginteger.h \
           LixTalk-client/rapidjson/internal/diyfp.h \
           LixTalk-client/rapidjson/internal/dtoa.h \
           LixTalk-client/rapidjson/internal/ieee754.h \
           LixTalk-client/rapidjson/internal/itoa.h \
           LixTalk-client/rapidjson/internal/meta.h \
           LixTalk-client/rapidjson/internal/pow10.h \
           LixTalk-client/rapidjson/internal/regex.h \
           LixTalk-client/rapidjson/internal/stack.h \
           LixTalk-client/rapidjson/internal/strfunc.h \
           LixTalk-client/rapidjson/internal/strtod.h \
           LixTalk-client/rapidjson/internal/swap.h \
           LixTalk-client/rapidjson/msinttypes/inttypes.h \
           LixTalk-client/rapidjson/msinttypes/stdint.h
FORMS += LixTalk-client/LixTalk.ui LixTalk-client/MainWindow.ui
SOURCES += LixTalk-client/client.cpp \
           LixTalk-client/DbConnector.cpp \
           LixTalk-client/LixTalk.cpp \
           LixTalk-client/main.cpp \
           LixTalk-client/MainWindow.cpp
RESOURCES += LixTalk-client/LixTalk.qrc
